### ISSUE TITLE
Create a more comprehensive dev environment setup explanation 

### ISSUE THREAD

**Issue by Rinzii** [cpp-gamedev/facade#18]
The current break down for setting up a dev environment for the project is pretty lack luster and would benefit from a rewrite covering in detail some of the most popular ide.

since this project is covering a much more complicated topic we should aim to make setup easier so people can get started faster!

**Comment by karnkaul** [comment]
Totally agree, but I'd also say that's not a priority right now unless a collaborator gets blocked in the process. I'd say for now "use CMake (presets) in whatever IDE you like" is sufficient; if an external collaborator can't figure that out I doubt they'd be able to contribute at this stage.

**Comment by karnkaul** [comment]
Added a wiki page that can be updated without needing to push commits to the main repo:
https://github.com/cpp-gamedev/facade/wiki/Development

This augments the existing [CONTRIBUTING.md](https://github.com/cpp-gamedev/facade/blob/main/.github/CONTRIBUTING.md) in the main repo.

**Comment by Rinzii** [comment]
I think for now this issue can be closed as the wiki post is more than necessary for the current state of the project.
