### ISSUE TITLE
Setup GitHub Actions CI

### ISSUE THREAD

**Issue by karnkaul** [cpp-gamedev/facade#3]
AC:
- [ ] Windows x64
  - [ ] Visual Studio | Release
- [ ] Linux x64
  - [ ] Ninja Multi-Config / gcc | Release
  - [ ] Ninja Multi-Config / clang | Release
- [ ] Prefer speed of response if something breaks over exhaustive job sets

[Reference](https://github.com/vulkify/vulkify/blob/main/.github/workflows/ci.yml)

**Comment by Rinzii** [comment]
Added in a starter file but it will likely need some tuning before it works correctly. I’ll go over it more tomorrow. ^^
